version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: ws_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ws_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - ws_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ws_app"]
      interval: 10s
      timeout: 5s
      retries: 5

  # オプション: pgAdmin（データベース管理ツール）
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: ws_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@ws-app.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - ws_network
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  ws_network:
    driver: bridge
